name: ethiopical
description: A Dart library for managing and converting dates between the Ethiopian and Gregorian calendars.
version: 1.0.0
repository: https://github.com/zomaye/ethiopical

environment:
  sdk: '>=2.19.0'

# Add regular dependencies here.
dependencies:
  intl: ^0.17.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
